### ISSUE TITLE
Using LocalGPT with external server which hosts ollama (via ngrok)

### ISSUE THREAD

**Issue by pfrankov** [pfrankov/obsidian-local-gpt#11]
<sup>Originally posted by **0xSynth** January 17, 2024</sup>
Hi, I can't run ollama mixtral model on my desktop, however I have a server to which I would like to connect (via ngrok), however for some reason I can't, is it a bug? Can you add this?

![Screenshot 2024-01-17 at 11 20 56](https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/2c2b59e1-a1b7-4707-9eb5-b2fba42f0c05)
</div>

**Comment by pfrankov** [comment]
@0xSynth I moved the discussion to an issue. Please provide some more information: how do you run Ollama on your desktop? Have you tried to send regular curl to the server?

**Comment by 0xSynth** [comment]
Thank you for quick response, I run obsydian with local-gpt plugin on my desktop. The server is running ollama, the server is accessible via a ngrok tunel and it works fine with https://github.com/kghandour/Ollama-SwiftUI, also requests are accessible via an API - I've tried requests via curl.

**Comment by pfrankov** [comment]
Thank you for the additional info!
I've just tried with ngrok `ngrok http 11434` and it it works for me right from the box:
<img width="788" alt="image" src="https://github.com/pfrankov/obsidian-local-gpt/assets/584632/1c039118-2880-4b4e-bbba-947bb55cd086">  
<img width="821" alt="image" src="https://github.com/pfrankov/obsidian-local-gpt/assets/584632/d20696e5-6f07-486a-b102-77e2418abd89">  
Please double check the settings, try to remove plugin and install again, try to update Ollama.

> Having an input where the default model name could be typed in would help in those kind of situations.

It's pointless to specify a model name using input — if you can't get a list of available models, then Ollama is unavailable.

**Comment by 0xSynth** [comment]
Supper strange, for me none of those `GET /api/tags` requests are hitting the server. I only get POST generate when trying to use the plugin in the article.

<img width="416" alt="Screenshot 2024-01-18 at 12 31 01" src="https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/2a9e1d9c-ade2-4ec1-bfbb-9e7e428f28e3">

**Comment by 0xSynth** [comment]
The console does not show any GET /api/tags request from the app being set to the server either.

<img width="1822" alt="Screenshot 2024-01-18 at 12 36 56" src="https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/872fe89a-4b4d-4ab4-91d5-9f2b900372da">

**Comment by 0xSynth** [comment]
I have downloaded the orca-mini and as a result I am able to use local-gpt, however the problem still persists - not being able to choose a model in the settings page.

<img width="1822" alt="Screenshot 2024-01-18 at 14 53 49" src="https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/9cf8ff1c-4932-42dc-8fe1-d54be2281238">

**Comment by pfrankov** [comment]
Have you tried to kill Ollama client and run Ollama in serve mode `OLLAMA_ORIGINS='*' ollama serve`?

**Comment by 0xSynth** [comment]
Yes I did, without OLLAMA_ORIGINS='*' the requests are getting 403, for me the issue is that for some reason after updating the API URL, the request to /api/tags are not being sent.

**Comment by pfrankov** [comment]
> the request to /api/tags is not being sent

That's expected: Obsidian's internal requests doesn't shown in Network tab. And errors from it also not visible in Console.  

Have you tried with regular `http://localhost:11434`? It seems that even this is failing with an error (while it shouldn't with with `OLLAMA_ORIGINS='*' ollama serve`) 
<img width="408" alt="image" src="https://github.com/pfrankov/obsidian-local-gpt/assets/584632/ac5b533d-febe-413e-893a-17435d98d1fd">

**Comment by pfrankov** [comment]
<video src="https://github.com/pfrankov/obsidian-local-gpt/assets/584632/a4b17baa-e689-40d9-b155-5939dd6d7c42"/>

**Comment by 0xSynth** [comment]
I was talking about the server side also, on your screenshots they are visible, however for some reason those are not sent to my server.
Regarding the localhost, it just an error when I had the Ollama URL set to localhost

**Comment by pfrankov** [comment]
> it just an error when I had the Ollama URL set to localhost

Nothing happen after that?

Let's exclude possible causes one by one: could you try to install and use the same scenario with the [BMO Chatbot plugin](https://github.com/longy2k/obsidian-bmo-chatbot)?

**Comment by 0xSynth** [comment]
Thank you for your recording, for me this refresh default model does not work for some reason, the request are not being sent to the server, at the same time I am able to run the plugin with `orca-mini` and requests are hitting the server

**Comment by 0xSynth** [comment]
Ok, I think we are onto something, with BMO Chatbot I am getting an error

<img width="888" alt="Screenshot 2024-01-18 at 21 46 47" src="https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/c3752485-d17e-47e4-b232-5604ba8d0c97">

The website when visible with incognito mode looks like this, maybe this is the issue? On the other hand you are also on free plan and it does work for you...
Meybe the solution would be to hit the `GET api/tags` directly without verifying the `GET /` if ngrok is used?

<img width="1007" alt="Screenshot 2024-01-18 at 21 46 33" src="https://github.com/pfrankov/obsidian-local-gpt/assets/95237361/3081656e-1c50-48d7-879c-685f9e4fb351">

**Comment by 0xSynth** [comment]
Ok, in the end I've decided to fork your plugin and change the default model to the one I like to use - works fine, however the issue still remains.

**Comment by quantarion** [comment]
I would drop support for the Ollama protocol and retain only OpenAI. All engines used for locally deploying LLMs have OpenAI compatibility modes in one form or another, including Ollama. The development effort would be much more useful if focused on adding new features rather than debugging VPNs, firewalls, tunnels, and similar issues. Regarding tunneling, I confirm that SSH tunneling works fine with Ollama (in OpenAI compatibility mode), Exllama (TabbyAPI), Aphrodite, and llama.cpp (in OpenAI mode).
