### ISSUE TITLE
right-click context menu

### ISSUE THREAD

**Issue by quantarion** [pfrankov/obsidian-local-gpt#13]
Hi,

Can you integrate the context menu into the obsidian right-click context menu? It would be really great!

**Comment by pfrankov** [comment]
Hi! Thank you for the idea!
I think that there is no benefits to put anything additional into main context menu since you can summon local-gpt's menu using customizable keyboard shortcut.

**Comment by quantarion** [comment]
In case you care, here's main.ts with action items moved to the right-click context menu. Feel free to ignore it, its your plugin after all.
[r-c-c-m.patch](https://github.com/pfrankov/obsidian-local-gpt/files/15473080/r-c-c-m.patch)
