### ISSUE TITLE
Feature: add editor context menu

### ISSUE THREAD

**Issue by vensauro** [pfrankov/obsidian-local-gpt#18]
I wish to see the prompts in the editor menu, like this: 
![image](https://github.com/user-attachments/assets/b4a2c3d2-115b-46a6-9bd3-6b790bba7cbd)

**Comment by pfrankov** [comment]
Hi there! Thank you for the idea!
Unfortunately it duplicates https://github.com/pfrankov/obsidian-local-gpt/issues/13 with provided alternative solution
