### ISSUE TITLE
[feature request] Support vim mode

### ISSUE THREAD

**Issue by melMass** [pfrankov/obsidian-local-gpt#21]
Hi,

Thanks this is the best one I found.
One little request would be to be able to use j/k to navigate the menu in vim mode

**Comment by pfrankov** [comment]
Hi!
The context menu is nothing special but regular context menu in your OS.
So it should work as expected in your OS.

**Comment by melMass** [comment]
Thanks it doesn't.
I'm referring to obs vim mode, but I will fork this project
