### ISSUE TITLE
All actions had been reset after updated the plugin

### ISSUE THREAD

**Issue by colin4k** [pfrankov/obsidian-local-gpt#29]
Can it provide a function to save the actions in order to protect them not to be reset?

**Comment by pfrankov** [comment]
That's weird. There is no any code that can reset actions.
If you have a different installation or a friend who didn't updated yet — you can provide `.obsidian/plugins/local-gpt/data.json` before update and right after that. This is the only thing that could possible help me to investigate the source of the issue.
Before that I'll close the issue.
