### ISSUE TITLE
No settings button (gear icon) displayed (Windows)

### ISSUE THREAD

**Issue by FitzFrobozz** [pfrankov/obsidian-local-gpt#3]
1. Installed via BRAT
2. Browsed to plugin
3. Settings button (gear icon) is not displayed next to plugin

![image](https://github.com/pfrankov/obsidian-local-gpt/assets/152919968/39c15e1c-a04f-4e31-93d2-bba7b351a421)

Perhaps this does not yet have Windows support?

Edit: my Obsidian version (v1.5.2):

![image](https://github.com/pfrankov/obsidian-local-gpt/assets/152919968/55bf26da-e977-4a6b-bf33-9f6740850519)

**Comment by pfrankov** [comment]
Thank you for the report. You're right: I've tested everything except the very first run.
Fixed in https://github.com/pfrankov/obsidian-local-gpt/releases/tag/1.4.2
Please check and reply.

By the way, you can now install plugin from Obsidian store https://obsidian.md/plugins?id=local-gpt

**Comment by FitzFrobozz** [comment]
Confirmed, appreciate the quick fix!

![image](https://github.com/pfrankov/obsidian-local-gpt/assets/152919968/8ebb1fbe-b9aa-488d-b1b5-16961e497b93)

> By the way, you can now install plugin from Obsidian store

Fwiw simply updating the plugin in Obsidian also works.
