### ISSUE TITLE
Canvas Enables Quick Tips, the quick window position is abnormal.

### ISSUE THREAD

**Issue by KaiDesigns** [pfrankov/obsidian-local-gpt#33]
I like this plugin, I encountered the following issue when calling in Canvas: the position of the shortcut window is not below the text.

<img width="2042" alt="image" src="https://github.com/user-attachments/assets/def947fa-9f9d-4030-9e1e-f70d5295792f">

**Comment by pfrankov** [comment]
Have no idea how to handle it. Probably it's a bug in Obsidian itself. Feel free to create a Pull request.
