### ISSUE TITLE
No context window shown

### ISSUE THREAD

**Issue by qinjie** [pfrankov/obsidian-local-gpt#34]
I have installed ollama locally (mac). In plugin setting, I am able to select lamma3.2 and bge-m3. But when I select the text in the editor, there is no context window shown up. I have restarted Obsidian.

**Comment by pfrankov** [comment]
Try to open Command Palette (Ctrl+P or Cmd+P) and find `LocalGPT: Show context menu` or make a hotkey
<img width="561" alt="image" src="https://github.com/user-attachments/assets/01b34ba3-368e-4229-b364-13fb3890e31f">

**Comment by qinjie** [comment]
Thank you for your swift response! It works now.
