### ISSUE TITLE
401 displayed when using the plugin

### ISSUE THREAD

**Issue by qidianlinjin1990** [pfrankov/obsidian-local-gpt#35]
401 errors are displayed when using providers in openai format in versions 1.12.0 and 1.13.0, but not in version 1.11.0. Providers include one-api and SiliconCloud, among others.
![Screenshot_2024-10-07-15-57-45-205_md obsidian](https://github.com/user-attachments/assets/5d28efe3-6768-4e1d-b7fb-1b7d50d9e996)

**Comment by pfrankov** [comment]
Have you tried with OpenAI API?

**Comment by qidianlinjin1990** [comment]
For some reason, it's not very convenient for me to directly use OpenAI, so I use third-party intermediaries that support OpenAI models, as well as some open-source large model platforms. These all support the OpenAI format, and they were supported in version 1.11.0, but I don't know why they are no longer supported in versions 1.12.0 and 1.13.0. 😂

**Comment by pfrankov** [comment]
Then I need your API URL, your API key ~~and your motorcycle~~.
Can you write me DM in [Telegram](https://t.me/pavel_frankov) or [LinkedIn](https://ru.linkedin.com/in/frankov)?

**Comment by qidianlinjin1990** [comment]
No problem, my API URL is https://api.siliconflow.cn, and the API key is sk-axokbbdufdmgpllldawgizivbfparhahatstrfmxowerekqy. You can use it directly.

**Comment by qidianlinjin1990** [comment]
You can choose the deepseek v2.5 model.

**Comment by pfrankov** [comment]
<img width="730" alt="Снимок экрана 2024-10-07 в 13 16 38" src="https://github.com/user-attachments/assets/b96928ce-2e82-4824-a510-79e835e0951a">
<img width="805" alt="image" src="https://github.com/user-attachments/assets/e4242a46-48a4-41ab-ab30-37104e4fc0a4">
It works for me. I assume that this is a network issue.

**Comment by qidianlinjin1990** [comment]
I set it up properly, and I can also choose the model, but it shows 401 when I use it. Have you used it?

**Comment by pfrankov** [comment]
Sure! The first screenshot is a proof.

Try to curl the API:
```
curl -XPOST -H 'Authorization: Bearer sk-axokbbdufdmgpllldawgizivbfparhahatstrfmxowerekqy' -H "Content-type: application/json" -d '{
  "model": "deepseek-ai/DeepSeek-V2.5",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Who won the world series in 2020?"
    }
  ]
}' 'https://api.siliconflow.cn/v1/chat/completions'
```

**Comment by qidianlinjin1990** [comment]
I'm using a mobile device, could it be because of that?

**Comment by pfrankov** [comment]
You're right. It happens only on mobile. I'll fix this for mobile but for now you can use 1.11.0

**Comment by qidianlinjin1990** [comment]
Thank you very much, I'll wait for the fixed version
