### ISSUE TITLE
Using this with Ollama + Open WebUI

### ISSUE THREAD

**Issue by stefanoco** [pfrankov/obsidian-local-gpt#43]
Anyone successfully using this (very useful) plugin in connection to a locally served Open WebUI API? I'm struggling trying to interact with it without success. After having tested the WebUI API with curl commands looks like it's functional

**Comment by pfrankov** [comment]
Could you please be more specific and describe some context along with the steps to reproduce.

**Comment by 2o1o0** [comment]
Hello,
I have a similar issue here.
I have openwebui installed and exposed, so I can now use ollama either through the openwebui or via the api with a token.
With VSCode addon, you [can achieve this](https://docs.openwebui.com/tutorials/integrations/continue-dev/) as openwebui and ollama have compatibility with open api specs. However you need to use the [useLegacyCompletionsEndpoint](https://docs.continue.dev/customize/model-providers/openai#openai-compatible-servers--apis) to have it working properly for some completion usage.
When I set it up with this addon, following the same rule for the url and api key, I'm unable to list/select a model. I don't see any log coming on the ollama server. If I try to use a feature like fix/review document, its just spin but no error that I can see.

![image](https://github.com/user-attachments/assets/f8b3ff49-4dca-4fff-bccc-4762f59ce76f)

![image](https://github.com/user-attachments/assets/2b102de6-3154-4c68-93e7-842564647d5a)

Thanks!

**Comment by 2o1o0** [comment]
Nevermind, it working like a charm, the only change I had to do was switch the url from `https://mydomain/ollama/v1` to `https://mydomain/ollama`

![image](https://github.com/user-attachments/assets/37cbbf3d-22be-4825-9f03-fbeee973a27b)

So I confirm that your addon is working fine so far with openwebui (helm chart v3.5.0).

**Comment by stefanoco** [comment]
Thanks to the comments above, I managed to have it work myself also! So anyone who might be in trouble with the same setup (local Ollama + WebUI service, API Key provided by WebUI) the endpoint to be specified should be set to something similar to the above.

Additionally, looks to me like whenever you try different formats for the endpoint address you'd better delete and rewrite again the API key. Dunno why but in my case changing the endpoint address to the correct one didn't work first; when I accidentally deleted the API Key and had to copy/paste again, everything started working. Might me a fault in my side so just a side note.
