### ISSUE TITLE
Add option to set context length in Ollama models

### ISSUE THREAD

**Issue by funghetto** [pfrankov/obsidian-local-gpt#45]
It would be appreciated to have an option to increase context length, useful when dealing with large texts.
The commands to set it are here: https://github.com/ollama/ollama/blob/main/docs/faq.md

**Comment by funghetto** [comment]
Do you mean when using a long context window size in Ollama or when selecting a large text of many pages and calling Ollama to process it from obsidian?

**Comment by pfrankov** [comment]
Look, you’re asking to make an option to set context length. I’m asking if there any issues right now with context length. What’s your case? Why you asking to make such option?

**Comment by funghetto** [comment]
Searching in the code it seems it is already dynamically adjusting it, so there is no issue for my case.
