### ISSUE TITLE
How to load ollama models like SmolLLM2

### ISSUE THREAD

**Issue by mad1mystic** [pfrankov/obsidian-local-gpt#48]
How can we load small LLM models like smolLLM2 via this plugin?  Ex https://ollama.com/library/smollm2:135m

**Comment by pfrankov** [comment]
`ollama pull smollm2:135m` and then select the model in the Local GPT settings in Obsidian.

**Comment by mad1mystic** [comment]
Sorry I didn't elaborate! I meant how to load small models like smolLLM2 on mobiles ! Android and IPhone ! It would be nice feature to have such models load directly via this plugin  . for reference you can check pocketpal AI its open source . would be wonderful plugin to load such models directly on phone for grammar and text related prompts . thank you
