### ISSUE TITLE
REQ: Local Rag Support

### ISSUE THREAD

**Issue by iamhenry** [pfrankov/obsidian-local-gpt#55]
Local GPT is great and i love what you've built

I use it for journal entries and was wondering if you can integrate a simple RAG solution?

When i write my journal entries i look for :
- Patterns and behaviors from previous notes
- Insights I may not notice my self

I have a custom system prompt that analysis my current note, but would love to be able to use RAG to reference all my notes for a better assessment

I would use an embeddeding from Ollama
<img width="960" alt="image" src="https://github.com/user-attachments/assets/f3d9d98a-7ce2-4683-abe1-096c36324c50">

**Comment by iamhenry** [comment]
I was aware but thanks for clarifying. I wasn't sure how to use it

So because of the limitation of the local models it's not currently possible?

I'm curious to hear your thoughts on how the plugin Smart Composer is able to accomplish it?

I'm not able to get the embed model working with that plugin so I prefer to use Local GPT since it automatically detects the models for me

https://github.com/glowingjade/obsidian-smart-composer

**Comment by pfrankov** [comment]
> I'm curious to hear your thoughts on how the plugin Smart Composer is able to accomplish it?

It doesn't.
If you have embedded entire vault and take only 10 chunks from it it's completely a blind luck to get useful results.

But I must say that there is a difference between Smart Composer and Local GPT: Smart Composer has fuzzy search (like regular search) and Local GPT doesn't have yet. This could be a little boost to the quality in some cases but not for all.

As I've said Local GPT has **the best** way to work with local documents for local models.
